Repository Smooth-2025/drivecast-service, pull requests merged in 2025-08, with the labels that each got.

#27 feat. STOMP WebSocket 서버 기본 설정
  src/main/java/com/smooth/alert_service/config/WebSocketConfig.java
  src/main/java/com/smooth/alert_service/controller/TestAlertController.java
Labels: TASK

#31 feat. 사고 유형별 알림 메시지 매핑 로직 및 테스트 추가
  src/main/java/com/smooth/alert_service/domain/AlertType.java
  src/main/java/com/smooth/alert_service/dto/AlertEvent.java
  src/main/java/com/smooth/alert_service/dto/AlertMessageDto.java
  src/main/java/com/smooth/alert_service/mapper/AlertMessageMapper.java
  src/main/java/com/smooth/alert_service/validator/AlertEventValidator.java
  src/test/java/com/smooth/alert_service/mapper/AlertMessageMapperTest.java
Labels: TASK

#33 feat: Redis를 이용한 중복 알림 방지 로직 추가
  src/main/java/com/smooth/alert_service/api/test/TestAlertController.java
  src/main/java/com/smooth/alert_service/api/test/TestTokenController.java
  src/main/java/com/smooth/alert_service/config/SessionEventListener.java
  src/main/java/com/smooth/alert_service/core/AlertEventHandler.java
  src/main/java/com/smooth/alert_service/core/AlertMessageMapper.java
  src/main/java/com/smooth/alert_service/core/AlertRepeatNotifier.java
  src/main/java/com/smooth/alert_service/core/VicinityUserFinder.java
  src/main/java/com/smooth/alert_service/model/AlertEvent.java
  src/main/java/com/smooth/alert_service/model/AlertMessageDto.java
  src/main/java/com/smooth/alert_service/model/AlertType.java
  src/main/java/com/smooth/alert_service/model/EventType.java
  src/main/java/com/smooth/alert_service/repository/AlertCacheService.java
  src/main/java/com/smooth/alert_service/security/JwtProperties.java
  src/main/java/com/smooth/alert_service/security/JwtTokenProvider.java
  src/main/java/com/smooth/alert_service/support/util/AlertIdResolver.java
  src/main/java/com/smooth/alert_service/support/validator/AlertEventValidator.java
  src/test/java/com/smooth/alert_service/mapper/AlertMessageMapperTest.java
  src/test/java/com/smooth/alert_service/redis/AlertCacheServiceTest.java
  src/test/java/com/smooth/alert_service/scheduler/AlertRepeatNotifierTest.java
  src/test/java/com/smooth/alert_service/service/VicinityUserFinderTest.java
Labels: TASK

#34 refactor: 반경 필터링 시 location:{timestamp} 최신 키 탐색 구조 적용
  src/main/java/com/smooth/alert_service/core/AlertRepeatNotifier.java
  src/main/java/com/smooth/alert_service/core/VicinityUserFinder.java
  src/main/java/com/smooth/alert_service/support/util/LatestLocationKeyFinder.java
Labels: TASK

#35 feat: 필터링된 대상에게 WebSocket 알림 전송 구현
  src/main/java/com/smooth/alert_service/core/AlertEventHandler.java
  src/main/java/com/smooth/alert_service/core/AlertMessageMapper.java
  src/main/java/com/smooth/alert_service/core/AlertRepeatNotifier.java
  src/main/java/com/smooth/alert_service/core/AlertSender.java
  src/main/java/com/smooth/alert_service/model/AlertMessageDto.java
  src/main/java/com/smooth/alert_service/repository/AlertCacheService.java
  src/main/java/com/smooth/alert_service/support/util/AlertIdResolver.java
  src/test/java/com/smooth/alert_service/mapper/AlertMessageMapperTest.java
  src/test/java/com/smooth/alert_service/redis/AlertCacheServiceTest.java
  src/test/java/com/smooth/alert_service/scheduler/AlertRepeatNotifierTest.java
  src/test/java/com/smooth/alert_service/service/VicinityUserFinderTest.java
Labels: TASK

#38 PR: US5.1 - 실시간 사고 알림 기능 구현 완료 → dev 머지
  src/main/java/com/smooth/alert_service/api/test/AlertTestController.java
  src/main/java/com/smooth/alert_service/config/RedisConfig.java
  src/main/java/com/smooth/alert_service/config/SessionEventListener.java
  src/main/java/com/smooth/alert_service/config/WebSocketConfig.java
  src/main/java/com/smooth/alert_service/core/AlertEventHandler.java
  src/main/java/com/smooth/alert_service/core/AlertMessageMapper.java
  src/main/java/com/smooth/alert_service/core/AlertRepeatNotifier.java
  src/main/java/com/smooth/alert_service/core/AlertSender.java
  src/main/java/com/smooth/alert_service/core/VicinityUserFinder.java
  src/main/java/com/smooth/alert_service/model/AlertEvent.java
  src/main/java/com/smooth/alert_service/model/AlertMessageDto.java
  src/main/java/com/smooth/alert_service/model/AlertType.java
  src/main/java/com/smooth/alert_service/model/EventType.java
  src/main/java/com/smooth/alert_service/repository/AlertCacheService.java
  src/main/java/com/smooth/alert_service/security/JwtProperties.java
  src/main/java/com/smooth/alert_service/security/JwtTokenProvider.java
  src/main/java/com/smooth/alert_service/support/util/AlertIdResolver.java
  src/main/java/com/smooth/alert_service/support/util/LatestLocationKeyFinder.java
  src/main/java/com/smooth/alert_service/support/validator/AlertEventValidator.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: USERSTORY

#39 refactor: api 값 변경 부분 수정 & 소켓-클라 연결 부분 수정
  src/main/java/com/smooth/alert_service/config/WebSocketConfig.java
  src/main/java/com/smooth/alert_service/model/AlertEvent.java
  src/main/java/com/smooth/alert_service/security/StompPrincipal.java
  src/main/java/com/smooth/alert_service/support/validator/AlertEventValidator.java
Labels: refactor

#42 Refactor us5.1
  src/main/java/com/smooth/alert_service/api/test/AlertTestController.java
  src/main/java/com/smooth/alert_service/config/RedisConfig.java
  src/main/java/com/smooth/alert_service/config/SessionEventListener.java
  src/main/java/com/smooth/alert_service/core/AlertSender.java
  src/main/java/com/smooth/alert_service/repository/AlertCacheService.java
  src/main/java/com/smooth/alert_service/support/util/LastSeenService.java
  src/main/java/com/smooth/alert_service/support/util/LatestLocationKeyFinder.java
Labels: refactor

#43 feat: US5.1 - KST 기반 시간 처리·반경 조회 재시도·본인 사고 우선 알림
  src/main/java/com/smooth/alert_service/core/AlertRepeatNotifier.java
  src/main/java/com/smooth/alert_service/core/VicinityUserFinder.java
  src/main/java/com/smooth/alert_service/support/util/AlertIdResolver.java
  src/main/java/com/smooth/alert_service/support/util/KoreanTimeUtil.java
Labels: feat

#44 fix: US5.1 - KST 타임스탬프 파싱 적용
  src/main/java/com/smooth/alert_service/core/AlertEventHandler.java
Labels: fix

#51 PR: T5.2.2 - 실시간 STOMP 전송 로직 구현 → US5.2 머지
  src/main/java/com/smooth/drivecast_service/driving/constants/DrivingVicinityPolicy.java
  src/main/java/com/smooth/drivecast_service/driving/service/DrivingBroadcastScheduler.java
  src/main/java/com/smooth/drivecast_service/driving/service/DrivingCoordinateService.java
  src/main/java/com/smooth/drivecast_service/driving/service/DrivingEventHandler.java
  src/main/java/com/smooth/drivecast_service/driving/service/DrivingSessionManager.java
Labels: TASK

#56 PR: T5.3.3 - 응급 연락처 조회 및 feign 구현 → US5.3 머지
  src/main/java/com/smooth/drivecast_service/emergency/feign/InternalController.java
  src/main/java/com/smooth/drivecast_service/emergency/feign/UserServiceClient.java
  src/main/java/com/smooth/drivecast_service/emergency/feign/UserServiceClientFallback.java
  src/main/resources/application-prod.yml
Labels: TASK

#58 PR: US5.2 - 주변 운전자 성향 실시간 전송 → dev 머지
  docker-compose.yml
  lombok.config
  src/main/java/com/smooth/drivecast_service/DrivecastServiceApplication.java
  src/main/java/com/smooth/drivecast_service/driving/constants/DrivingDestinations.java
  src/main/java/com/smooth/drivecast_service/driving/constants/DrivingVicinityPolicy.java
  src/main/java/com/smooth/drivecast_service/driving/dto/DrivingCoordinate.java
  src/main/java/com/smooth/drivecast_service/driving/dto/DrivingDestinations.java
  src/main/java/com/smooth/drivecast_service/driving/dto/DrivingResponseDto.java
  src/main/java/com/smooth/drivecast_service/driving/dto/TraitBulkResponseDto.java
  src/main/java/com/smooth/drivecast_service/driving/dto/TraitResponseDto.java
  src/main/java/com/smooth/drivecast_service/driving/exception/DrivingErrorCode.java
  src/main/java/com/smooth/drivecast_service/driving/feign/UserTraitClient.java
  src/main/java/com/smooth/drivecast_service/driving/feign/test/MockTraitTestController.java
  src/main/java/com/smooth/drivecast_service/driving/feign/test/MockUserTraitController.java
  src/main/java/com/smooth/drivecast_service/driving/service/DrivingBroadcastScheduler.java
  src/main/java/com/smooth/drivecast_service/driving/service/DrivingCoordinateService.java
  src/main/java/com/smooth/drivecast_service/driving/service/DrivingEventHandler.java
  src/main/java/com/smooth/drivecast_service/driving/service/DrivingSessionManager.java
  src/main/java/com/smooth/drivecast_service/driving/service/DrivingTraitService.java
  src/main/java/com/smooth/drivecast_service/driving/service/DrivingVicinityService.java
  src/main/java/com/smooth/drivecast_service/driving/service/TraitCacheService.java
  src/main/java/com/smooth/drivecast_service/driving/service/mapper/DrivingMessageMapper.java
  src/main/java/com/smooth/drivecast_service/driving/service/mapper/EndMessageMapper.java
  src/main/java/com/smooth/drivecast_service/driving/service/mapper/StartMessageMapper.java
  src/main/java/com/smooth/drivecast_service/driving/util/LocationWindowKeyGenerator.java
  src/main/java/com/smooth/drivecast_service/global/common/location/WindowGeoSearchAdapter.java
  src/main/java/com/smooth/drivecast_service/global/common/location/WindowLocationAdapter.java
  src/main/java/com/smooth/drivecast_service/global/util/KoreanTimeUtil.java
  src/main/java/com/smooth/drivecast_service/global/util/ValidationUtil.java
  src/main/java/com/smooth/drivecast_service/incident/constants/IncidentDestinations.java
  src/main/java/com/smooth/drivecast_service/incident/dto/IncidentDestinations.java
  src/main/java/com/smooth/drivecast_service/incident/dto/IncidentEvent.java
  src/main/java/com/smooth/drivecast_service/incident/dto/IncidentResponseDto.java
  src/main/java/com/smooth/drivecast_service/incident/service/IncidentEventHandler.java
  src/main/java/com/smooth/drivecast_service/incident/service/IncidentRepeatNotifier.java
  src/main/java/com/smooth/drivecast_service/incident/service/mapper/AccidentMessageMapper.java
  src/main/java/com/smooth/drivecast_service/incident/service/mapper/IncidentMessageMapper.java
  src/main/java/com/smooth/drivecast_service/incident/service/mapper/ObstacleMessageMapper.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: USERSTORY

#59 PR: refactor - US5.3 feign 주소 변경 → feat-US5.3 머지
  src/main/java/com/smooth/drivecast_service/emergency/feign/UserServiceClient.java
Labels: refactor

#60 PR: refactor - US5.3 위도 경도 타입 및 prod 환경 설정 → feat-US5.3 머지
  src/main/java/com/smooth/drivecast_service/emergency/entity/EmergencyReport.java
  src/main/java/com/smooth/drivecast_service/emergency/feign/dto/EmergencyReportDto.java
  src/main/java/com/smooth/drivecast_service/emergency/service/EmergencyReportService.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: refactor

#61 PR: US5.3 - 119 자동 신고 서비스 → dev 머지
  build.gradle
  src/main/java/com/smooth/drivecast_service/DrivecastServiceApplication.java
  src/main/java/com/smooth/drivecast_service/emergency/controller/EmergencyReportController.java
  src/main/java/com/smooth/drivecast_service/emergency/dto/AccidentInfoDto.java
  src/main/java/com/smooth/drivecast_service/emergency/dto/EmergencyReportResult.java
  src/main/java/com/smooth/drivecast_service/emergency/dto/EmergencyRequestDto.java
  src/main/java/com/smooth/drivecast_service/emergency/dto/EmergencyUserInfoDto.java
  src/main/java/com/smooth/drivecast_service/emergency/entity/EmergencyReport.java
  src/main/java/com/smooth/drivecast_service/emergency/exception/EmergencyErrorCode.java
  src/main/java/com/smooth/drivecast_service/emergency/feign/InternalController.java
  src/main/java/com/smooth/drivecast_service/emergency/feign/UserServiceClient.java
  src/main/java/com/smooth/drivecast_service/emergency/feign/UserServiceClientFallback.java
  src/main/java/com/smooth/drivecast_service/emergency/feign/dto/EmergencyInfoResponse.java
  src/main/java/com/smooth/drivecast_service/emergency/feign/dto/EmergencyReportDto.java
  src/main/java/com/smooth/drivecast_service/emergency/repository/EmergencyReportRepository.java
  src/main/java/com/smooth/drivecast_service/emergency/service/EmergencyReportService.java
  src/main/java/com/smooth/drivecast_service/emergency/service/SmsService.java
  src/main/java/com/smooth/drivecast_service/emergency/service/mapper/EmergencyMapper.java
  src/main/java/com/smooth/drivecast_service/global/common/cache/DedupService.java
  src/main/java/com/smooth/drivecast_service/global/common/cache/RedisDedupService.java
  src/main/java/com/smooth/drivecast_service/global/config/CorsConfig.java
  src/main/java/com/smooth/drivecast_service/global/config/TwilioConfig.java
  src/main/java/com/smooth/drivecast_service/incident/service/IncidentEventHandler.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: USERSTORY

#62 PR: refactor-US5.3 - 119 자동 신고 서비스 리팩토링 → feat-US5.3 머지
  build.gradle
  src/main/java/com/smooth/drivecast_service/emergency/entity/EmergencyReport.java
  src/main/java/com/smooth/drivecast_service/emergency/feign/UserServiceClientFallback.java
  src/main/java/com/smooth/drivecast_service/emergency/repository/EmergencyReportRepository.java
  src/main/java/com/smooth/drivecast_service/emergency/service/EmergencyReportService.java
  src/main/java/com/smooth/drivecast_service/emergency/service/mapper/EmergencyMapper.java
  src/main/resources/application.yml
Labels: refactor
