Repository Smooth-2025/drivecast-service, pull requests merged in 2025-09, with the labels that each got.

#63 PR: US5.3 - 119 자동 신고 서비스 리팩토링 → dev 머지
  build.gradle
  src/main/java/com/smooth/drivecast_service/emergency/entity/EmergencyReport.java
  src/main/java/com/smooth/drivecast_service/emergency/feign/UserServiceClientFallback.java
  src/main/java/com/smooth/drivecast_service/emergency/repository/EmergencyReportRepository.java
  src/main/java/com/smooth/drivecast_service/emergency/service/EmergencyReportService.java
  src/main/java/com/smooth/drivecast_service/emergency/service/mapper/EmergencyMapper.java
  src/main/resources/application.yml
Labels: USERSTORY

#66 PR: refactor - DEV Mock 테스트 파일 정리 & OpenFeign 엔드포인트 수정 → dev 머지
  src/main/java/com/smooth/drivecast_service/driving/feign/UserTraitClient.java
  src/main/java/com/smooth/drivecast_service/driving/feign/test/MockTraitTestController.java
  src/main/java/com/smooth/drivecast_service/driving/feign/test/MockUserTraitController.java
  src/main/java/com/smooth/drivecast_service/incident/dto/IncidentResponseDto.java
Labels: refactor

#67 PR: refactor - DEV WebSocket 설정 개선 (허용 오리진, 스케줄러, 하트비트 조정) → dev 머지
  src/main/java/com/smooth/drivecast_service/global/config/WebSocketConfig.java
Labels: refactor

#68 PR: refactor - DEV WebSocket 엔드포인트 "/ws" → "/wss" 변경 → dev 머지
  src/main/java/com/smooth/drivecast_service/global/config/WebSocketConfig.java
Labels: refactor

#70 PR: fix - DEV WebSocket 엔드포인트 /wss → /ws 복원 → dev 머지
  src/main/java/com/smooth/drivecast_service/global/config/WebSocketConfig.java
Labels: fix

#73 PR: refactor - 관리자 대시보드 사고 이력 조회 api 변경 → dev 머지
  src/main/java/com/smooth/drivecast_service/emergency/controller/AccidentController.java
  src/main/java/com/smooth/drivecast_service/emergency/dto/EmergencyResponseDto.java
  src/main/java/com/smooth/drivecast_service/emergency/feign/InternalController.java
  src/main/java/com/smooth/drivecast_service/emergency/repository/EmergencyReportRepository.java
  src/main/java/com/smooth/drivecast_service/emergency/service/EmergencyReportService.java
Labels: refactor

#74 PR: feat - DEV Jenkinsfile 개선 & Redis Pub/Sub 기반 알림 기능 테스트 → dev 머지
  Jenkinsfile
  build.gradle
  src/main/java/com/smooth/drivecast_service/driving/dto/DrivingCoordinate.java
  src/main/java/com/smooth/drivecast_service/driving/dto/TraitBulkResponseDto.java
  src/main/java/com/smooth/drivecast_service/driving/dto/TraitResponseDto.java
  src/main/java/com/smooth/drivecast_service/driving/feign/UserTraitClient.java
  src/main/java/com/smooth/drivecast_service/driving/service/DrivingBroadcastScheduler.java
  src/main/java/com/smooth/drivecast_service/driving/service/DrivingTraitService.java
  src/main/java/com/smooth/drivecast_service/driving/util/LocationWindowKeyGenerator.java
  src/main/java/com/smooth/drivecast_service/emergency/service/EmergencyReportService.java
  src/main/java/com/smooth/drivecast_service/global/common/location/LocationKeyGenerator.java
  src/main/java/com/smooth/drivecast_service/global/common/location/VicinityUserFinder.java
  src/main/java/com/smooth/drivecast_service/global/common/messaging/ConnectionHeartbeatScheduler.java
  src/main/java/com/smooth/drivecast_service/global/common/messaging/GlobalConnectionManager.java
  src/main/java/com/smooth/drivecast_service/global/common/messaging/KickMessageListener.java
  src/main/java/com/smooth/drivecast_service/global/common/messaging/LocalConnectionManager.java
  src/main/java/com/smooth/drivecast_service/global/common/messaging/PubSubMessageListener.java
  src/main/java/com/smooth/drivecast_service/global/common/messaging/RealtimeEnvelope.java
  src/main/java/com/smooth/drivecast_service/global/common/messaging/RealtimeMessage.java
  src/main/java/com/smooth/drivecast_service/global/common/notification/RealtimePublisher.java
  src/main/java/com/smooth/drivecast_service/global/common/notification/StompRealtimePublisher.java
  src/main/java/com/smooth/drivecast_service/global/common/pod/PodInfo.java
  src/main/java/com/smooth/drivecast_service/global/config/RedisConfig.java
  src/main/java/com/smooth/drivecast_service/global/config/SessionEventListener.java
  src/main/java/com/smooth/drivecast_service/global/config/WebSocketConfig.java
  src/main/java/com/smooth/drivecast_service/global/controller/HealthController.java
  src/main/java/com/smooth/drivecast_service/global/security/JwtProperties.java
  src/main/java/com/smooth/drivecast_service/global/security/JwtTokenProvider.java
  src/main/java/com/smooth/drivecast_service/global/util/AuthenticationUtils.java
  src/main/java/com/smooth/drivecast_service/incident/service/IncidentEventHandler.java
  src/main/resources/application.yaml
  src/test/resources/application.yaml
Labels: feat
